### ISSUE TITLE
[8.0] Build status is red

### ISSUE THREAD

**Issue by dreispt** [OCA/project#110]
Probably related to #97

**Comment by antespi** [comment]
Hi @dreispt, could you restart this travis https://travis-ci.org/OCA/project/builds/78278293?
This build is from September 1st, but there's a Odoo commit (https://github.com/odoo/odoo/commit/64e1c28e358ec06a7683249fd7fae1ba631c1933) that I think that break project_sla tests
Thank you

**Comment by pedrobaeza** [comment]
I have restarted to see.

**Comment by antespi** [comment]
It's red because `get_working_intervals_of_day` has changed, now it's TZ dependant, so if dates are in UTC, then tests must include `{'tz': 'UTC'}` in context like https://github.com/odoo/odoo/commit/64e1c28e358ec06a7683249fd7fae1ba631c1933 does

I do the same in this commit https://github.com/OCA/project/commit/f868a9181d659c2440a50e6e325ad2ae5b99f5c8 for fixing `project_recalculate` because I set start/end times that aren't comming from user.

@dreispt you're author of `project_sla` addon, could you review this and confirm?
Thanks

**Comment by dreispt** [comment]
Thanks for tracing that change. I read the diff but I can't help feeling there's something smelly about it.
Yes, I'll need to take some time to look at it and fix `project_sla`.

**Comment by antespi** [comment]
Thanks @dreispt
