### ISSUE TITLE
[8.0]  project_issue_task - Incorrect description or incorrect functionality

### ISSUE THREAD

**Issue by rafaelbn** [OCA/project#140]
module:  project_issue_task 
version: 8.0

**Steps to reproduce**
- Read description

```
    'description': """\
Support for the use case where solving an Issue means a Task should be done,
such as an on site visit, and a report must be made to document the work done.
This is a common scenario in technical field services.
The Issue form already has a "Task" field, allowing to create a Task related
to an Issue.
This module adds some usability improvements:
  * "Create Task" button on the Issue form [Wrong name]
  * Automaticaly Close the Issue when the Task is Closed [BUG]
  * Automatically Cancel the Task when Issue is Cancelled [BUG]
  * Make the Task also visible to all followers of the related Issue [BUG]
""",
```

**Current behavior**
- If you go to an issue you will see a button "Task Report" and not "Create Task", name is incorrect but funcionallity is OK? (Button creates a project.task)
  ![2015-12-12_2-39-26](https://cloud.githubusercontent.com/assets/8736623/11759392/b820d85c-a079-11e5-97df-3b28eba55ca1.png)
-  But if you close the task, the issue is not closed
  ![2015-12-12_2-43-09](https://cloud.githubusercontent.com/assets/8736623/11759427/6ab70aa4-a07a-11e5-8437-35f18eb7b806.png)
- And if the issue is cancelled the task is not cancelled
  ![2015-12-12_2-46-38](https://cloud.githubusercontent.com/assets/8736623/11759469/bae3b568-a07a-11e5-8415-524f968d62f4.png)
- Task is not visible to all followers of the related issue

**Expected behavior**
- "Create Task" button on the Issue form [Wrong name]
- Automaticaly Close the Issue when the Task is Closed [BUG]
- Automatically Cancel the Task when Issue is Cancelled [BUG]
- Make the Task also visible to all followers of the related Issue [BUG]

**Comment by rafaelbn** [comment]
Ref for improvements: https://github.com/projectexpert/pmis/tree/8.0/project_task_issues

**Comment by dreispt** [comment]
The current label name came from a to an implementation specific usage and yes, it should be corrected.

The sync logic was probably dropped when moving to 8.0, because in 8.0 `state` was removed.
But `project_stage_state` restored states, so with it you could restore the 7.0 logic.
But I wonder if this logic is not too opinionated - maybe it should instead be done per implementation, using Automated Actions?

Also, I found the Issue/task syncing to be complex, so I stopped using it since 8.0. Instead I now just use Tasks with additional initial stages, where they are in an "Issue" phase.
That means that I'm not maintaining the module anymore, so you're welcome to work on it.

**Comment by rafaelbn** [comment]
CLosing, too old!
