### ISSUE TITLE
v80 project_issue_task not working

### ISSUE THREAD

**Issue by cmsalmeida** [OCA/project#152]
There is not even a action_close anywhere on other modules

**Comment by pedrobaeza** [comment]
I'm using it and is working. Please be more specific in "what" is not working.

**Comment by cmsalmeida** [comment]
In what Odoo version you use it?
When one moves a task to a final stage, how Odoo knows that it's final stage to close issue also?

**Comment by dreispt** [comment]
@cmsalmeida I guess your issue is that there is no sync between Task and Issue once the Task is closed or cancelled.
Yes this logic was there in v7 but was lost since v8 removed stages.
We could still detect when the Task moves to a "folded" Stage and sync that to the Issue.

But on the functional side, IMO that's too opinionated: if you need that sync I suggest using an Automated Action for it.
Having said that, `action_close` is dead code and should be removed.

**Comment by cmsalmeida** [comment]
That was I thought off...

And, also the link to task (m2o) is set, but not the one from task to issue :)

We use tko_project_issue_to_task but we don't got task<-->issue state sync also.

But we can think toghether to make it work:
1. We can add a selection field to stage that states it as a final stage ex: start, end.
2. Or do like it is done in opportunities, the stage has a probability field, and we can use it to know that. If it's 100% it's final.
