### ISSUE TITLE
RFC: Project Agile

### ISSUE THREAD

**Issue by lasley** [OCA/project#205]
One of the major things keeping me from migrating my PM from JIRA into Odoo is the lack of agile functionality. This RFC is a planning/call to arms to solve a problem that we are all likely having.

There are basically two types of agile, so I see there being two base modules:

* Scrum - Sprint based development
  * Sprint opens with a planned end time
  * Only active sprint is displayed to users in non-planning view
      * Let's forget about the planning view for the moment though, that's a whole different nut to crack
  * Sprint closes, open cards are moved to next Sprint in sequence
  * Next sprint in sequence is moved to active
* KanBan - Release based development. Sucks that this name clashes with Odoo's, so we'll probably just call it Release
  * All open issues are displayed to users
  * Release closes, closed cards are moved from active view and tagged to release

The reporting is very different between the two, but we can worry about that later. I'm wondering if we have anything that sort of fits these requirements already? They're fairly high level at this point in order to try and be as open minded as possible in regards to actual workflow.

**Comment by rafaelbn** [comment]
Hi @lasley , true... we have a big hole here... It was https://github.com/odoo/odoo/tree/6.1/addons/project_scrum, but not enough

INHO this is a very common need yo all of us (Software base companies - OCA contributors) @Tecntiva @Yajo @antespi @pedrobaeza @sergio-teruel @carlosdauden @cubells @jbeficent

**Comment by jcdrubay** [comment]
I would be interested in participating, starting by sharing what we do.

For us we have created 2 new concepts:
- Sprint: with starting date and ending date (name is the ending date). As a simplification, our sprint are always one week long.
- Release

Each task is linked to a sprint and a release. From the list view of task, we can easily remove / move to previous/next sprint/release.

Then it is possible to do any of both agile methods (if I understand correctly).

Key reports are:
- Group by sprint of the tasks: gives a total workload per sprint to ensure that our capacity matches the workload so we can deliver on time. It also gives the current Burndown for the current sprint.
- Group by release for a project: shows progress on the overall project / burndown of the release
- Velocity can be mesured with a group by "code complete date" of the task.

Some key numbers from us:
- it is quite common for us to have 100 tasks open for a project so I am really afraid of a Kanban view with 100 cards opened. I don't think Kanban view makes sense when you have more than 20 active cards
- per release, we try not to have more than 20 tasks
- for our ideal project, we have one release = 1 sprint. But it happens rarely.
- it is quite common that several release are active at the same time: 1.0 in production + 2.0 in customer testing + 3.0 ready for customer testing but waiting for testing of 2.0 to be completed + 4.0 in fine-tuning internally + 5.0 active developments

Side notes: 
- We don't have story points, everything is measured in estimated hours of workload with some rough estimates on remaining workload per task:
  - WIP: max(estimate - time spent, 50%of total estimate)
  - Code complete: 70% of total estimated is considered as done
  - Code reviewed: 80% of total estimated is considered as done
  - Task closed : 100% of total estimated is considered as done
- Additionally we have the concept of Functional Block (a simple object with 2 fields: name and project_id) which allows us to group the tasks and facilitate delegation and reduce merge conflicts (one functional block per team member). It could be considered as a User Story.
- there are some modules published by Elico Corp (see their presentation [here](https://www.odoo.com/slides/slide/manage-your-customer-business-requirements-in-odoo-488)) which are related to project management.

**Comment by pedrobaeza** [comment]
@jbeficent has developed a vertical about project management. Please see possible overlaps.

**Comment by pedrobaeza** [comment]
And you also need to check what Odoo is doing for v11, putting focus on services companies.

**Comment by JordiBForgeFlow** [comment]
I think Agile needs it's own dedicated repo. It is governed by specific rules that are very different to traditional project management. Otherwise, when some starts testing on the OCA/project repo this can be a mess....

OCA/project could be used for common modules
OCA/project-agile, for agile approach
OCA/project-iso21500 for traditional approach

My 2 cents.

**Comment by JordiBForgeFlow** [comment]
cc @dreispt

**Comment by JordiBForgeFlow** [comment]
@sysadminmatmoz

**Comment by lasley** [comment]
@jcdrubay Excellent notes, thank you.

@pedrobaeza good note regarding Odoo 11. Some Googling yielded [the specs sheet that they will be using to build the feature](https://docs.google.com/document/d/1cotLe6NPdA_DN5_W5s10NUh4AjiZAb-JHnKKakoWE-A/edit#heading=h.sgq33csxtja0), so we seem to have a good idea of what they'll be offering. Looks like we'll be getting a lot of great features, but I don't see anything agile still.

@jbeficent I agree that it is a good idea to split the concepts. TIL about ISO-21500.

**Comment by dreispt** [comment]
@jbeficent Specialized repos are the way to go.

If I recall correctly, we had a proposal from @mileo to move the work at https://github.com/kmee/project-agile into the OCA. That could be a base to build on. The process is to make green on Travis CI, and then move ownership to the  OCA.

**Comment by pedrobaeza** [comment]
Seeing that repo, it seems that there is overlap with business requirements.

**Comment by sysadminmatmoz** [comment]
Hi all.

It does overlap, @pedrobaeza, but it does not conflict with it. It's just a different approach.
The BR module tries to encode project resources and deliverables inside the BR document, ISO approach is, that resources and deliverables get planned on project. The main difference is in the concept, when a project starts; the usual "layman" approach is: the project starts when the order is confirmed, a project oriented company approach on the other hand is: the project starts when the lead is received, the requirements/order/similar confirmation means only a stage change in the project (confirmed sale could mean the switch from the initiation to the planning stage for example).

Agile approach is actually a PM framework and is actually a part of traditional PM; it's suited mostly for project operations management and non-complex projects (like software industry, where the approach was born or reinvented, since it's not a new approach, it was just wrapped in a new terminology pack) so again, not in conflict, since I manage lots of my project by classical methodology, but allow the agile framework to manage the project operations.

**Comment by lasley** [comment]
Yeah I'm thinking they're complementary like @sysadminmatmoz noted. I see agile as being the method by which the tasks are worked, and BR being the method by which they are defined. If you have a lot of consecutive epic-type projects running in the long term, I could see the need for sprints & releases on top of the requirements.

@mileo can you please confirm that you would allow the transition of your repo into OCA? It seems this does indeed allow for a nice base, so I would love to see it here 😄

**Comment by dreispt** [comment]
@lasley @mileo I had a better look at the repo, and I think that in this case it will be easier if we create a new repo from scratch, and then use per-module PRs, like we did for Business Requirements.

It's also my opinion that a specific repo for agile and scrum methodologies is a good thing, and we should make sure that the features it brings are complementary to BRs.

**Comment by lasley** [comment]
New repos are always good; it makes things explicitly clear that the two versions are different & allows for more drastic changes between them.

> we should make sure that the features it brings are complementary to BRs.

We should also consider the non-use of BRs. I typically don't have need for these, except on the rare event that my customers need custom dev work.

**Comment by mileo** [comment]
Hi, 

We are using https://github.com/kmee/project-agile in our odoo implementation projects since 08/03/2016

It's works reasonably but with some improvements it would be very good.

Our team was discussing today that it would be very nice to have an integration with the BR modules.

We are planning to do that.

**Comment by dreispt** [comment]
Wrapping up this Issue, https://github.com/OCA/project-agile was created, to host Agile specific modules.
Contributions there are welcome - both code and reviews.
ATM it will cover all flavors of Agile, such as Scrum. If the needed arises , flavor specific repos could be created.
