### ISSUE TITLE
[10.0]project_closing module. Translations files were recreated

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/project#428]
Project closing was removed from this repo in v10.0 here https://github.com/OCA/project/pull/357
However OCA Transbot recreated the files: https://github.com/OCA/project/tree/10.0/project_closing/i18n

Removing those files again would be enough?

**Comment by pedrobaeza** [comment]
Now with Weblate I think it is. Previously on Transifex it wasn't.

@sbidoul can you confirm the POT cleaning?

**Comment by sbidoul** [comment]
AFAIK we never tested removing an addon that is on weblate.

That said,
- weblate has a different project/component for each branch
- if you remove an addon from a branch when it is already in weblate, there will be a merge conflict if/when weblate tries to push it back to github, so we'll know when that happens because it will barf at us :)

So yes, go ahead and remove those files, they will not be recreated.
