### ISSUE TITLE
project_task_material

### ISSUE THREAD

**Issue by ghost** [OCA/project#477]
I have detected this behaviour and I don't if this is the correct.
I have tried on runbot add a material on a task. Sometimes when the analytic entry is made, the cost of the material is registered. I think it's correct.
![1](https://user-images.githubusercontent.com/25029267/53554164-74332c80-3b3f-11e9-8dab-fca021933331.png)
The cost of the product is 25.
![3](https://user-images.githubusercontent.com/25029267/53554359-d2600f80-3b3f-11e9-886d-4f965753377b.png)
But then, I have created other task in the same project and I have added the same material and the cost is not registered when the analytic entry has been made.
![2](https://user-images.githubusercontent.com/25029267/53554419-fb80a000-3b3f-11e9-8f41-4f9b33efc8ea.png)
I have tried on other projects and the cost is not registered. 
I don't know if it isn't correct or if there are some conditions have to be met to record the cost when the analytical entry is created

Then, I have detected too that if you move the task to other stage the analytic entry disappears

**Comment by bennals** [comment]
@gelo-landoo I have also found that analytic entries do not have an 'amount' associated with them, in fact in the short time I've been looking at project_task_material it hasn't happened at all.  If it happened once for you then it must be a configuration issue, but I'd love to know what it is.

**Comment by bennals** [comment]
@gelo-landoo you may have already discovered this but it's a reported issue (I'm assuming you have sale_timesheet installed).  The related pull request for the fix is here:
https://github.com/OCA/project/pull/462

and the module to fix the problem is here:
https://github.com/jcarlosmontoya/project/tree/11.0-project_task_material_sale_timesheet

I just checked it and it seems to work well.
