### ISSUE TITLE
[13.0] Error when entering Tasks and returning to Projects

### ISSUE THREAD

**Issue by Robssilva30** [OCA/project#754]
Hello, I installed the Module and after accessing the Timeline Vision, then viewing the tasks, when I try to return to the Projects Page through the link in the header, the following error is presented below

______________________________________________________________________________________________________

**Traceback:
update@https://localhost/web_timeline/static/src/js/timeline_controller.js:53:17
OdooClass.extend/</prototype[name]</<@https://localhost/web/static/src/js/core/class.js:90:38
reload@https://localhost/web/static/src/js/views/abstract_controller.js:228:33
_switchController/controllerDef</<@https://localhost/web/static/src/js/chrome/action_manager_act_window.js:551:50**

______________________________________________________________________________________________________

Analyzing the JavaScript code, I found the following error:

**Uncaught (in promise) TypeError: n_group_bys is undefined**

Thank You!

**Comment by skeller1** [comment]
https://user-images.githubusercontent.com/226753/103183414-8e143680-48b2-11eb-9f0d-42d7b0d2a55d.mp4

Also noticed this problem.
There's a change between Odoo V12 and Odoo V13 (click on smart button in opened form in dialog mode).

This [check in timeline_controller.js](https://github.com/OCA/web/blob/2c866f0a3e50517da0747c1c208df557bdad010a/web_timeline/static/src/js/timeline_controller.js#L40) fails:

```
if (_.isEmpty(params)) {
                return res;
            }
```
params should be empty (or empty object), but is is an object with an empty breadcrumbs array. So the return is not executed.

The problem must be fixed in web_timeline addon. Maybe @Tardo could give some feedback.
Thank you

**Comment by Robssilva30** [comment]
Thanks @skeller1, I will wait for news in this module
