### ISSUE TITLE
project_timeline: Module modification

### ISSUE THREAD

**Issue by AndreyZhulanov** [OCA/project#933]
module: project_timeline
version: 14.0

hi! 

**Steps to reproduce**
- 

**Current behavior**

**Expected behavior**

We are interested in your Odoo module project_timeline. We need several upgrades of the module for our purposes. Is it possible to ask you to develop changes we need? We'll pay for development.
Our needs:
1) To see all tasks of our employees in all projects within one window. It helps us to see how many tasks each employee has at the moment;
2) It should be the way to hide the UNASSIGNED line or to move it down the list on timeline window;
3) " Extra Info tab" should be visible not only in the developers mode. Now it is.

Please recommend somebody who can help us if you couldn't

**Comment by francesco-ooops** [comment]
Hi @AndreyZhulanov , if you don't have devs available to work on OCA modules, you can find groups on telegram such as "odoo developers" where you should be able to find someone to hire (check their rules about work offers anyway)

Consider that changing features in OCA modules must be done by keeping in mind the needs of users already emplyoing the module (eg: maybe the're a reason "Extra info" is only available in developer mode)

**Comment by aps2201** [comment]
Can I reopen this since this has also been an issue with me? I see people here don't want to change it for some reason.

> Consider that changing features in OCA modules must be done by keeping in mind the needs of users already emplyoing the module (eg: maybe the're a reason "Extra info" is only available in developer mode)

I found  PR from a  year ago that claimed "Because setting them manually without the timeline view is not the usual way" https://github.com/OCA/project/pull/1335#issuecomment-2334056817 but I can't understand that reasoning also. If we create the task from the timeline view you still need access to the extra_info tab so it doesn't seem to explain anything. Anyway I did an edit to addons/project/project_timeline/views/project_task_view.xml around line 109
```
<field name="inherit_id" ref="project.view_task_form2" />
        <field name="arch" type="xml">
            <xpath expr="//page[@name='task_dependencies']" position="after">
            	<page name="timeline_plan" string='Timeline'>
                <field
                    name="planned_date_start"
                    widget="daterange"
                    options="{'end_date_field': 'planned_date_end'}"
                    string="Planned Dates"
                />
                <field name="planned_date_end" invisible="1" />
                </page>
            </xpath>
        </field>
```

This creates a new tab "Timeline" in the form, but somehow I can't label them (which is fine since it serves my purpose) . I have yet to see any negative impacts for myself but is there really any?
