### ISSUE TITLE
Improvement of Unique Constrains on Project Key 

### ISSUE THREAD

**Issue by yweng8111** [OCA/project#966]
**Module:**
project_key

**Problem and Solutions:**
I want to install the module project_key in a DB which contains some Projects with the same Name but different company_id. The Hook script in this module tries to generate the key for every project. But the function generate_project_key of project doesn't consider the company_id and show me the error of the unique constrains .

Can we just change the constrains like this?
```
    _sql_constraints = [
        ("project_key_unique", "UNIQUE(key, company_id)", "Project key must be unique")
    ]
```
If you think that the key must be unique, We can also improve the function generate_project_key with an extra parameter "company_id" and return the new key (old key + company_id).

What do you think?

**Comment by marylla** [comment]
I think the current way to create project keys is very error-prone. 
We have a lot of projects that are very similiar and therefore have a similiar naming scheme.
We can not install the module after years of using Odoo, due to this hook and unique contraint.

At least we should consider the company in this unique-contraint as @yweng8111 suggested, but I think the hook should be totally different. What about a hash value or maybe just an ...easy numbering?

@pedrobaeza @dreispt What do you think? Do you see a better solution?

**Comment by pedrobaeza** [comment]
I agree. I don't like this module at all. The uniqueness should be checked only for manual assigned keys. For automatic ones, there should be a loop until one key is free, using for example a counter.

**Comment by yweng8111** [comment]
@pedrobaeza Thanks. I will try to improve the function like you suggested.
